# configs/config.yaml
seed: 0

optimization:
  learning_rate: 1e-4
  batch_size: 2056
  epochs: 30000

model:
  type: mlp
  hidden_layers: [64,64]
  prior_std: 0.1
  ff: None
  ff_amplitudes: False

defaults:
  - posterior: sbvi
  - dataset: sin
  - _self_

  
