# configs/config.yaml
seed: 0

optimization:
  learning_rate: 1e-4
  batch_size: 2056
  epochs: 100

model:
  type: mlp
  hidden_layers: []
  prior_std: 0.01
  ff: None
  ff_amplitudes: False

defaults:
  - posterior: sbvi
  - dataset: spiked_linear
  - _self_

  
