# configs/config.yaml
seed: 0

optimization:
  optimizer: adamW
  learning_rate: 1e-3
  batch_size: 32
  epochs: 1000

model:
  type: mlp
  hidden_layers: [16, 16]
  prior_std: 0.33
  ff: None
  ff_amplitudes: True

defaults:
  - posterior: mfvi
  - dataset: sin
  - _self_
